exp_name: "3_pb_model_penalty"

x_vars: ['seg_ccov', 'seg_rain', 'seg_slope', 'seg_tave_air', 'seginc_swrad', 'hru_slope', 'hru_aspect', 'hru_elev', 'hru_area', 'hru_percent_imperv', 'covden_sum', 'covden_win', 'soil_moist_max']

y_vars: ['do_min', 'do_mean', 'do_max', 'GPP', 'ER', 'K600', 'depth', 'temp.water', 'hru_elev', 'light_ratio']

meta_lambdas: [1, 1, 1]

epochs: [2]

num_replicates: 1


